apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-kafka
spec:
  serviceName: {{ .Chart.Name }}-kafka
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        prometheus.io/scrape: "{{ .Values.monitoring.prometheus }}"
    spec:
      containers:
      - name: kafka
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
