# SSL Configuration
cert_dir: "/etc/kafka/ssl"
cert_expiry_days: 90
key_size: 2048
country: "US"
state: "California"
locality: "San Francisco"
organization: "Kafka Deployment"
organizational_unit: "Security"
email: "security@example.com"

lets_encrypt:
  enabled: false
  email: ""
  staging: true
  domains: []
