# Cloud Provider Integration
aws:
  use_acm: false
  region: us-east-1
  domain: ""
  acm_arn: ""

gcp:
  managed_certs: false
  project_id: ""
  location: "us-central1"
  ca_name: ""

k8s:
  csr_enabled: false
  signer_name: "kubernetes.io/kube-apiserver-client"

# Audit logging
audit:
  max_entries: 1000
  retention_days: 365

