---
- name: Install monitoring stack
  hosts: kafka_cluster
  tasks:
    - name: Collect hardware specs
      shell: |
        echo "cpu_cores=$(nproc)" > /tmp/hw_specs
        echo "disk_type=$(lsblk -d -o rota | tail -1)" >> /tmp/hw_specs
        echo "network_speed=$(ethtool eth0 | grep Speed | awk '{print $2}')" >> /tmp/hw_specs
      register: hw_info

    - name: Store hardware profile
      template:
        src: templates/hw_profile.j2
        dest: /etc/prometheus/hw_profile.yml

    - name: Install NVMe tools
      apt:
        name: nvme-cli
        state: present
      when: "'NVME' in ansible_devices"

    # Existing monitoring tasks below...

