- name: Configure AlertManager
  helm:
    name: prometheus
    chart_name: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    values:
      alertmanager:
        config:
          global:
            resolve_timeout: 5m
          route:
            group_by: ['alertname']
            receiver: 'default'
          receivers:
          - name: 'default'
            email_configs:
            - to: 'alerts@example.com'
              send_resolved: true
      prometheus:
        prometheusSpec:
          ruleSelectorNilUsesHelmValues: false

- name: Apply Kafka alert rules
  k8s:
    state: present
    definition: "{{ lookup('file', '../../charts/kafka/templates/prometheusrules.yaml') | from_yaml }}"

