cluster_name: "test-cluster"
kafka_version: 3.2.0
zookeeper_version: 3.7.1
monitoring:
  enabled: true
  prometheus_exporters:
    jmx: true
    node: true
  alert_rules:
    cpu_alert_threshold: 90
    disk_alert_threshold: 85
    consumer_lag_threshold: 10000

