cluster_name: "test-cluster"
kafka_version: 3.2.0
zookeeper_version: 3.7.1
nodes:
  - ip: 192.168.1.10
    user: admin
    role: broker
  - ip: 192.168.1.11
    user: admin
    role: zookeeper
  - ip: 192.168.1.12
    user: admin
    role: both

tuning_params:
  num_partitions: 3
  replication_factor: 2
  log_retention_hours: 168
